@baseUrl = http://localhost:3000


### RecadosController

# @name RecadosController

GET {{baseUrl}}/recados
###

GET {{baseUrl}}/recados/10
###

POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Recado de teste novo",
    "de": "Sistema",
    "para": "Usuário"   
}

###
PATCH {{baseUrl}}/recados/8/
Content-Type: application/json

{    
  "lido": true,
  "texto": "Teste6"
}

###
DELETE  {{baseUrl}}/recados/10/






